### ISSUE TITLE
Экран MainScreen

### ISSUE THREAD

**Issue by Qwan-Chi** [Leftbrained-Inc/multimark#37]
```[tasklist]
### Tasks
- [ ] https://github.com/Leftbrained-Inc/multimark/issues/60
- [ ] https://github.com/Leftbrained-Inc/multimark/issues/61
- [ ] https://github.com/Leftbrained-Inc/multimark/issues/62
- [ ] https://github.com/Leftbrained-Inc/multimark/issues/63
```
