### ISSUE TITLE
Сохранение файла

### ISSUE THREAD

**Issue by pank-su** [Leftbrained-Inc/multimark#82]
```[tasklist]
### Tasks
- [ ] https://github.com/Leftbrained-Inc/multimark/issues/145
- [ ] https://github.com/Leftbrained-Inc/multimark/issues/146
- [ ] https://github.com/Leftbrained-Inc/multimark/issues/137
```
