### ISSUE TITLE
Табы

### ISSUE THREAD

**Issue by pank-su** [Leftbrained-Inc/multimark#96]
```[tasklist]
### Tasks
- [ ] https://github.com/Leftbrained-Inc/multimark/issues/98
- [ ] https://github.com/Leftbrained-Inc/multimark/issues/99
- [ ] https://github.com/Leftbrained-Inc/multimark/issues/100
- [ ] https://github.com/Leftbrained-Inc/multimark/issues/101
- [ ] https://github.com/Leftbrained-Inc/multimark/issues/102
- [ ] https://github.com/Leftbrained-Inc/multimark/issues/103
- [ ] https://github.com/Leftbrained-Inc/multimark/issues/104
```
